### ISSUE TITLE
README instructions detail Node implementation

### ISSUE THREAD

**Issue by JakePeyser** [IBM-Bluemix/cf-deployment-tracker-client-java#1]
README instructions need to be updated to explain how to implement tracker in Java app

**Comment by ptitzler** [comment]
I've modified the instructions to describe the deployment steps for a simple Java web application. These instructions should work work with the Liberty for Java boilerplate templates (Java Cloudant Web Starter, Java DB Web Starter, etc) on http://www.bluemix.net.
